# Generated by Django 4.2.1 on 2023-05-30 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название узла')),
            ],
            options={
                'verbose_name': 'Узел/Сборка',
                'verbose_name_plural': 'Узлы/Сборки',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FileArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('md5', models.CharField(blank=True, max_length=100, null=True, verbose_name='MD5 сумма')),
                ('file', models.CharField(max_length=500, verbose_name='Путь к архиву')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_files', to='storage.assemblymodel', verbose_name='Узел/Сборка')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архивы',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='Не описано', max_length=5000, null=True, verbose_name='Описание')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='storage.categorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='FileHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('md5', models.CharField(blank=True, max_length=100, null=True, verbose_name='MD5 сумма')),
                ('file', models.FileField(upload_to=storage.models.upload_file_to, verbose_name='Архив')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_history_files', to='storage.assemblymodel', verbose_name='Узел/Сборка')),
                ('latest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_files', to='storage.filearchivemodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_history_files', to='storage.projectarchivemodel', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='filearchivemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='storage.projectarchivemodel', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='assemblymodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assembly', to='storage.projectarchivemodel', verbose_name='Проект'),
        ),
    ]
