# Generated by Django 4.2.1 on 2023-05-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectarchivemodel',
            name='description',
            field=models.TextField(default='Не описано', max_length=5000, verbose_name='Описание'),
        ),
    ]
