# Generated by Django 4.2.1 on 2023-05-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_projectarchivemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearchivemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_file', to='storage.projectarchivemodel', verbose_name='Проект'),
        ),
    ]
