# Generated by Django 4.2.1 on 2023-05-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_filearchivemodel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearchivemodel',
            name='file',
            field=models.FileField(upload_to='files/models/', verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='filearchivemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='storage.projectarchivemodel', verbose_name='Проект'),
        ),
    ]
