# Generated by Django 4.2.1 on 2023-05-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_filearchivemodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filearchivemodel',
            name='name',
            field=models.CharField(default='ProjectName', max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filearchivemodel',
            name='file',
            field=models.FileField(upload_to='storage/models/', verbose_name='Архив'),
        ),
    ]
