# Generated by Django 4.2.1 on 2023-05-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_filearchivemodel_name_alter_filearchivemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filearchivemodel',
            name='history',
            field=models.JSONField(blank=True, null=True, verbose_name='История изменений'),
        ),
    ]
