# Generated by Django 4.2.1 on 2023-05-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_filearchivemodel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearchivemodel',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
