# Generated by Django 4.2.1 on 2023-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_filearchivemodel_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectarchivemodel',
            options={'ordering': ['-id'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterField(
            model_name='projectarchivemodel',
            name='description',
            field=models.TextField(blank=True, default='Не описано', max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
