# Generated by Django 4.2.1 on 2023-05-19 10:26

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_filearchivemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearchivemodel',
            name='file',
            field=models.FileField(upload_to=storage.models.upload_file_to, verbose_name='Архив'),
        ),
    ]
